### PR TITLE
Smart project dashobard, task and meeting directives

### LINKED ISSUE #90: Add project viewer

### PR DESCRIPTION
**Pull request by mszynka**
project progres and many more magic

Closes #90 #89

### CODE REVIEW

**Comment by bojakowsky** [comment]
- [x] styles problem (calendar)


- [x] another styles problem (double frames, pop up always)
- [x] On Meetings and Tasks, I can assign users whcih are not even connected with Project
- [x] On tasks W/E time, add some spaces W / E, cause it's hardly readable
- [x] Not "watching" users on tasks, but task Executors
- [x] In some cases, for e.g. on Projects users can be added, but cannot be deleted, well.. on this one i loled hard ~Bojakowski.
- [x] Task GetAllWithStats is calling about 3 to 5 asynchronous calls, why?
- [x] Adding/Del users on tasks can make whole Task section throw exceptions - exceptions are thrown on GetAllWithStats Task controller method

[EDITED]
- [x] Style on projects simple dropdown gotta be repaired
- [x] Date on meetings is wrong, thus it can't be added - this how it looked like from backend - it was typo in meetings angular controller  - JSON.Stringify was returning [" "]
- [x] There occurs some bug on task adding, which throws exception on tasks loading
- [ ] Information that list does not contain elements pops up even if there're elements - after a sec it disappears, but for certain it's not what we want - REOPENED - it's better than it was, but still bleh
- [ ] Smth wrong is with the search engine

**Comment by mszynka** [comment]
@bojakowsky Yeah, this "cannot remove user" is your fault actually. 

``` c#
var users = container.Resolve<ApplicationUserManager>();
users.Users.First(x => x.Email == userId);
```

So essentially you send `user.First...` somewhere into space :wink:

OR
Why it's not working? I don't get that

**Comment by mszynka** [comment]
> Task GetAllWithStats is calling about 3 to 5 asynchronous calls, why?

Well. Thats cause it's used in foreach and I couldn't or didn't found out how or why to do this properly. Sorry for that potato...

**Comment by mszynka** [comment]
@bojakowsky This search engine 'fail'. It's how it works really. It's looking not only at name but every property of element, so presumably in Description.

**Pull request merged**
