### PR TITLE
Magic user manager

### PR DESCRIPTION
**Pull request by mszynka**
I think it's about time

### CODE REVIEW

**Comment by mszynka** [comment]
Fixing calendars

**Comment by bojakowsky** [comment]
ToDos:
Meetings
- [ ] Meeting needs a status (active, ended),
- [ ] On Meeting creation and meeting edit there should be some space to write a note (meeting note)
- [ ] Now there's only Meeting to project assignment, there should be also Meeting to project task assignment available (as dropdown to tasks or smth like that)

Tasks
- [x] UserPicker for task participants, 
- [x] In task list , number of participants should be printed
- [x] task owner should be also printed on the list
- [x] there should be number of hours (summed from worklogs assigned to task) printed

-Also tests need to be done

**Comment by mszynka** [comment]
But for the sake of presentation now we don't do those. Not on this branch
anyway

**Comment by mszynka** [comment]
@bojakowsky Meeting status is defined by date and time, isn't it? Cause you cannot have meeting in past. And you cannot have ended meeting in future. Am I wrong?

**Pull request merged**
